version: "3.9"

services:
  db:
    image: postgres:17
    container_name: fastapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: ailyzer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  minio:
    image: quay.io/minio/minio:latest
    container_name: ailyzer_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ailyzeradmin
      MINIO_ROOT_PASSWORD: ailyzeradmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: